// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK57eIE4wQuUxjI7cFrWap2lb6BTSAY38',
    appId: '1:541836126729:web:28187ac3442b7d5e70a6d8',
    messagingSenderId: '541836126729',
    projectId: 'yogawans-auth-app',
    authDomain: 'yogawans-auth-app.firebaseapp.com',
    storageBucket: 'yogawans-auth-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVy-25yPZibUcw0kvmHchf8wtehS3eCyg',
    appId: '1:541836126729:android:dacd315287564fe670a6d8',
    messagingSenderId: '541836126729',
    projectId: 'yogawans-auth-app',
    storageBucket: 'yogawans-auth-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDNI0qgyfVTdQnQ7mhkYMknjeiCU2A-RY',
    appId: '1:541836126729:ios:8a2f4260d2cf7b0870a6d8',
    messagingSenderId: '541836126729',
    projectId: 'yogawans-auth-app',
    storageBucket: 'yogawans-auth-app.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDNI0qgyfVTdQnQ7mhkYMknjeiCU2A-RY',
    appId: '1:541836126729:ios:8a2f4260d2cf7b0870a6d8',
    messagingSenderId: '541836126729',
    projectId: 'yogawans-auth-app',
    storageBucket: 'yogawans-auth-app.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK57eIE4wQuUxjI7cFrWap2lb6BTSAY38',
    appId: '1:541836126729:web:37d350355795b7ca70a6d8',
    messagingSenderId: '541836126729',
    projectId: 'yogawans-auth-app',
    authDomain: 'yogawans-auth-app.firebaseapp.com',
    storageBucket: 'yogawans-auth-app.firebasestorage.app',
  );

}